import './app-shell'
import './view-channel-search'
import './view-home'
import './view-not-found'
import './view-plot-settings'
import './view-query-meta'
import './view-plot'
import './view-preselect'
