import './view-channel-info'
import './view-channel-search'
import './view-home'
import './view-index-plot'
import './view-not-found'
import './view-plot-settings'
import './view-plot'
import './view-preselect'
